version: '3'

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_service
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  myapp:
    container_name: cloud_service
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/cloud_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres