version: "3.9"
services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_DB: "diplom_cloud_storage"
      POSTGRES_USER: "diplom_cloud_app"
      POSTGRES_PASSWORD: "diplom_cloud_app"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cloudapp:
    build: .
    container_name: cloudapp
    ports:
      - 8081:8080
    depends_on:
      - postgres